name: Build & publish module to registry 
on:
  release:
    types: [published]

# This regex matches either a semver (e.g. 1.2.3)
# or a release candidate in one of these forms:
# 1.2.3-rc or 1.2.3-rc1
# Adjust the regex below as needed.
# The pattern:
#   ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ 
# matches to
#    [0-9]+.[0-9]+.[0-9]+
# or [0-9]+.[0-9]+.[0-9]+-rc optionally followed by digits

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Validating tag: $TAG"
          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
            echo "Tag matches semver."
          else
            echo "Error: tag does not match semvar"
            exit 1
          fi

  publish:
    needs: validate-tag
    name: Build and Upload module 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Publish
        uses: viamrobotics/build-action@v1.4
        with:
          version: ${{ github.event.release.tag_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}

  publish-windows:
    needs: validate-tag
    name: Build and Upload Windows module
    runs-on: ${{ matrix.build_target.built_on }}
    strategy:
      matrix:
        build_target:
          - platform: windows/amd64
            built_on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -a -o module.exe ./cmd/module
      - name: Package
        run: tar -czf module.tar.gz module.exe third_party/onnxruntime.dll
      - name: Install Viam CLI
        run: |
          Invoke-WebRequest -Uri "https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-latest-windows-amd64.exe" -OutFile "viam.exe"
      - name: Publish build to Viam registry
        run: |
          .\viam.exe login api-key --key-id ${{ secrets.viam_key_id }} --key ${{ secrets.viam_key_value }}
          .\viam.exe module upload --platform ${{ matrix.build_target.platform }} --version ${{ github.ref_name }} module.tar.gz

